src/Entity/Interfaces/Modules/ModuleMainEntityInterface.php
<?php

namespace App\Entity\Interfaces\Modules;

/**
 * This interface should only be applied on entities which are directly representing elements of given module
 *  which further means that for example module can consist:
 *   - Issue,
 *   - IssueContact,
 *   - IssueProgress
 *
 * However the main Entity in that case would be Issue as it is the single entity which relates with additional one
 * and the additional one are not allowed to live as separate beings
 *
 * Interface ModuleMainEntityInterface
 */
interface ModuleMainEntityInterface {

    public function getRelatedModuleName(): string;

}

src/Entity/Interfaces/Modules/ModuleSubEntityInterface.php
<?php

namespace App\Entity\Interfaces\Modules;

/**
 * This interface should only be applied on sub/additional entities which relate somehow to the main Entity of given module
 * Check the description for @see ModuleMainEntityInterface
 * - so this is interface is for entity which as single being cannot represent module entry itself
 *
 * Interface ModuleSubEntityInterface
 */
interface ModuleSubEntityInterface {

}

src/Entity/Modules/Achievements/Achievement.php
<?php

namespace App\Entity\Modules\Achievements;

use App\Entity\Interfaces\EntityInterface;
use App\Entity\Interfaces\SoftDeletableEntityInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Modules\Achievements\AchievementRepository")
 */
class Achievement implements SoftDeletableEntityInterface, EntityInterface {

    public const ENUM_SIMPLE = 'simple';
    public const ENUM_MEDIUM = 'medium';
    public const ENUM_HARD = 'hard';
    public const ENUM_HARDCORE = 'hardcore';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", columnDefinition="ENUM('simple', 'medium', 'hard', 'hardcore')", nullable=false)
     */
    private $Type;

    /**
     * @ORM\Column(type="boolean")
     */
    private $deleted = 0;

    public function getId(): ?int {
        return $this->id;
    }

    public function getName(): ?string {
        return $this->Name;
    }

    public function setName(string $Name): self {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string {
        return $this->Description;
    }

    public function setDescription(?string $Description): self {
        $this->Description = $Description;

        return $this;
    }

    public function getType(): ?string {
        return $this->Type;
    }

    public function setType(string $Type): self {
        $this->Type = $Type;

        return $this;
    }

    public function isDeleted(): ?bool {
        return $this->deleted;
    }

    public function setDeleted(bool $deleted): self {
        $this->deleted = $deleted;

        return $this;
    }
}

src/Entity/Modules/Contacts/MyContact.php
<?php

namespace App\Entity\Modules\Contacts;

use App\DTO\Modules\Contacts\ContactsTypesDTO;
use App\Entity\Interfaces\EntityInterface;
use App\Entity\Interfaces\SoftDeletableEntityInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Modules\Contacts\MyContactRepository")
 */
class MyContact implements SoftDeletableEntityInterface, EntityInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="text", columnDefinition="LONGTEXT NOT NULL")
     */
    private $contacts;

    /**
     * @ORM\Column(type="boolean")
     */
    private $deleted = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imagePath;

    /**
     * @ORM\Column(type="text")
     */
    private $nameBackgroundColor;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $descriptionBackgroundColor;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Modules\Contacts\MyContactGroup", inversedBy="myContacts")
     * @ORM\JoinColumn(nullable=true)
     */
    private $group;

    /**
     * todo: check what happens if there are no contacts for this entry
     * Contacts in DB are stored as JSON bo we need dto to work with the data
     * @return ContactsTypesDTO
     * @throws \Exception
     */
    public function getContacts() {

        $json = $this->contacts;
        $dto = ContactsTypesDTO::fromJson($json);

        return $dto;
    }

    /**
     * @param string $contacts (json)
     */
    public function setContacts(string $contacts): void {
        $this->contacts = $contacts;
    }

    /**
     * @return string
     */
    public function getNameBackgroundColor() {
        return $this->nameBackgroundColor;
    }

    /**
     * @param mixed $nameBackgroundColor
     */
    public function setNameBackgroundColor($nameBackgroundColor): void {
        $this->nameBackgroundColor = $nameBackgroundColor;
    }

    /**
     * @return string
     */
    public function getDescriptionBackgroundColor() {
        return $this->descriptionBackgroundColor;
    }

    /**
     * @param string $descriptionBackgroundColor
     */
    public function setDescriptionBackgroundColor($descriptionBackgroundColor): void {
        $this->descriptionBackgroundColor = $descriptionBackgroundColor;
    }

    /**
     * @return string
     */
    public function getImagePath() {
        return $this->imagePath;
    }

    /**
     * @param string $imagePath
     */
    public function setImagePath($imagePath): void {
        $this->imagePath = $imagePath;
    }

    public function getId(): ?int {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void {
        $this->id = $id;
    }

    public function getName(): ?string {
        return $this->name;
    }

    /**
     * @param string $name
     * @return MyContact
     */
    public function setName(string $name): self {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string {
        return $this->description;
    }

    /**
     * @param string $description
     * @return MyContact
     */
    public function setDescription(?string $description): self {
        $this->description = $description;

        return $this;
    }

    public function isDeleted(): ?bool {
        return $this->deleted;
    }

    /**
     * @param bool $deleted
     * @return MyContact
     */
    public function setDeleted(bool $deleted): self {
        $this->deleted = $deleted;

        return $this;
    }

    public function getGroup(): ?MyContactGroup
    {
        return $this->group;
    }

    public function setGroup(?MyContactGroup $group): self
    {
        $this->group = $group;

        return $this;
    }

}

src/Entity/Modules/Contacts/MyContactGroup.php
<?php

namespace App\Entity\Modules\Contacts;

use App\Entity\Interfaces\EntityInterface;
use App\Entity\Interfaces\SoftDeletableEntityInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Modules\Contacts\MyContactGroupRepository")
 */
class MyContactGroup implements SoftDeletableEntityInterface, EntityInterface
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $icon;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $color;

    /**
     * @ORM\Column(type="boolean")
     */
    private $deleted = 0;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Modules\Contacts\MyContact", mappedBy="group")
     */
    private $myContacts;

    public function __construct()
    {
        $this->myContacts = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function getColor() {
        return $this->color;
    }

    /**
     * @param string $color
     */
    public function setColor(string $color): void {
        $this->color = $color;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function isDeleted(): ?bool
    {
        return $this->deleted;
    }

    public function setDeleted(bool $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getIcon() {
        return $this->icon;
    }

    /**
     * @param string $icon
     */
    public function setIcon(string $icon): void {
        $this->icon = $icon;
    }

    /**
     * @return Collection|MyContact[]
     */
    public function getMyContacts(): Collection
    {
        return $this->myContacts;
    }

    public function addMyContact(MyContact $myContact): self
    {
        if (!$this->myContacts->contains($myContact)) {
            $this->myContacts[] = $myContact;
            $myContact->setGroup($this);
        }

        return $this;
    }

    public function removeMyContact(MyContact $myContact): self
    {
        if ($this->myContacts->contains($myContact)) {
            $this->myContacts->removeElement($myContact);
            // set the owning side to null (unless already changed)
            if ($myContact->getGroup() === $this) {
                $myContact->setGroup(null);
            }
        }

        return $this;
    }

}

src/Entity/Modules/Contacts/MyContactType.php
<?php

namespace App\Entity\Modules\Contacts;

use App\Entity\Interfaces\EntityInterface;
use App\Entity\Interfaces\SoftDeletableEntityInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Modules\Contacts\MyContactTypeRepository")
 */
class MyContactType implements SoftDeletableEntityInterface, EntityInterface
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imagePath;

    /**
     * @ORM\Column(type="boolean")
     */
    private $deleted = 0;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function isDeleted(): ?bool
    {
        return $this->deleted;
    }

    public function setDeleted(bool $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getImagePath() {
        return $this->imagePath;
    }

    /**
     * @param mixed $imagePath
     */
    public function setImagePath($imagePath): void {
        $this->imagePath = $imagePath;
    }

}

src/Entity/Modules/Goals/MyGoalsPayments.php
<?php

namespace App\Entity\Modules\Goals;

use App\Entity\Interfaces\EntityInterface;
use App\Entity\Interfaces\SoftDeletableEntityInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Modules\Goals\MyGoalsPaymentsRepository")
 * @ORM\Table(name="my_goal_payment")
 */
class MyGoalsPayments implements SoftDeletableEntityInterface, EntityInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="date", length=255, nullable=true)
     */
    private $deadline;

    /**
     * @ORM\Column(type="integer")
     */
    private $moneyGoal;

    /**
     * @ORM\Column(type="integer")
     */
    private $moneyCollected;

    /**
     * @ORM\Column(type="boolean")
     */
    private $deleted = 0;

    /**
     * @ORM\Column(type="date", length=255)
     */
    private $collectionStartDate;

    /**
     * @ORM\Column(type="boolean")
     */
    private $displayOnDashboard = 0;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMoneyGoal(): ?int
    {
        return $this->moneyGoal;
    }

    public function setMoneyGoal(int $moneyGoal): self
    {
        $this->moneyGoal = $moneyGoal;

        return $this;
    }

    public function getMoneyCollected(): ?int
    {
        return $this->moneyCollected;
    }

    public function setMoneyCollected(int $moneyCollected): self
    {
        $this->moneyCollected = $moneyCollected;

        return $this;
    }

    public function isDeleted(): ?bool
    {
        return $this->deleted;
    }

    public function setDeleted(bool $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getDeadline() {
        return $this->deadline;
    }

    /**
     * @param $deadline
     * @return $this
     * @throws \Exception
     */
    public function setDeadline($deadline) {

        if( is_string($deadline) ){
            $deadline = new \DateTime($deadline);
        }

        $this->deadline = $deadline;

        return $this;
    }

    public function getCollectionStartDate() {
        return $this->collectionStartDate;
    }

    /**
     * @param $collectionStartDate
     * @return $this
     * @throws \Exception
     */
    public function setCollectionStartDate($collectionStartDate) {

        if( is_string($collectionStartDate) ){
            $collectionStartDate = new \DateTime($collectionStartDate);
        }

        $this->collectionStartDate = $collectionStartDate;

        return $this;

    }


    public function getDisplayOnDashboard(): ?bool
    {
        return $this->displayOnDashboard;
    }

    public function setDisplayOnDashboard(bool $displayOnDashboard): self
    {
        $this->displayOnDashboard = $displayOnDashboard;

        return $this;
    }

}

src/Entity/Modules/Job/MyJobSettings.php
<?php

namespace App\Entity\Modules\Job;

use App\Entity\Interfaces\EntityInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Modules\Job\MyJobSettingsRepository")
 * @ORM\Table(name="my_job_setting")
 */
class MyJobSettings implements EntityInterface{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $value;

    public function getId(): ?int {
        return $this->id;
    }

    public function getType(): ?string {
        return $this->type;
    }

    public function setType(string $type): self {
        $this->type = $type;

        return $this;
    }

    public function getValue(): ?string {
        return $this->value;
    }

    public function setValue(string $value): self {
        $this->value = $value;

        return $this;
    }
}

src/Entity/Modules/Notes/MyNotes.php
<?php

namespace App\Entity\Modules\Notes;

use App\Entity\Interfaces\EntityInterface;
use App\Entity\Interfaces\SoftDeletableEntityInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Modules\Notes\MyNotesRepository")
 * @ORM\Table(name="my_note")
 */
class MyNotes implements SoftDeletableEntityInterface, EntityInterface
{
    const KEY_DELETED = "deleted";

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Body;

    /**
     * @ORM\Column(type="boolean")
     */
    private $deleted = 0;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Modules\Notes\MyNotesCategories", inversedBy="note")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    public function getId(): ?int {
        return $this->id;
    }

    public function getTitle(): ?string {
        return $this->Title;
    }

    public function setTitle(string $Title): self {
        $this->Title = $Title;

        return $this;
    }

    public function getBody(): ?string {
        return $this->Body;
    }

    public function setBody(?string $Body): self {
        $this->Body = $Body;

        return $this;
    }

    public function isDeleted(): ?bool {
        return $this->deleted;
    }

    public function setDeleted(?bool $deleted): self {
        $this->deleted = $deleted;

        return $this;
    }

    public function getCategory(): ?MyNotesCategories {
        return $this->category;
    }

    public function setCategory(?MyNotesCategories $category): self {
        $this->category = $category;

        return $this;
    }
}

templates/modules/my-notes/category.html.twig
{% if ajax_render == false %}
    {% set template= "base.html.twig" %}
{% else %}
    {% set template= "blank.html.twig" %}
{% endif %}

{% extends template %}

{% block body %}
    <main class='main-content bgc-grey-100' id="noteCategory">
        <div id='mainContent'>
            <div class="container-fluid">

                <div class="row">
                    <div class="col-md-12">
                        <div class="bgc-white bd bdrs-3 p-10 mB-20 note-category-content-wrapper">
                            <h4 class="c-grey-900 mB-20 text-center">{{ category | capitalize }}</h4>

                            <section class="all-notes">
                                {% for note in notes %}

                                    {% set lock_record = note.id %}
                                    {% set lock_type   = constant('App\\Entity\\System\\LockedResource::TYPE_ENTITY') %}
                                    {% set lock_target = constant('App\\Controller\\Modules\\ModulesController::MODULE_NAME_NOTES') %}

                                    {% if isAllowedToSeeResource(lock_record, lock_type, lock_target) %}
                                        <section class="single-note-details d-flex save-parent">

                                        <span class="fas fa-lock {{ getClassForLockedResource(lock_record, lock_type, lock_target) }} align-self-center action-lock-record"
                                              data-lock-resource-record ="{{ lock_record }}"
                                              data-lock-resource-type   ="{{ lock_type }}"
                                              data-lock-resource-target ="{{ lock_target }}"
                                              data-toggle-popover="true"                                      {# popover attr #}
                                              data-content="{{ 'actions.popover.lockRecord' | trans }}"       {# popover attr #}
                                              data-placement="top"                                            {# popover attr #}
                                        ></span>

                                            <button type="button" class="btn btn-primary note-button" data-toggle="modal"
                                                    data-target="#note{{ note.id }}"
                                                    id="noteListElement{{ note.id }}"
                                            >
                                            <span>
                                                {{ note.title }}
                                            </span>
                                            </button>

                                            {% include 'modules/my-notes/components/note-edit-modal.html.twig' %}
                                        </section>
                                    {% endif %}
                                {% endfor %}
                            </section>

                        </div>
                    </div>
                </div>
            </div>

            <div class="widgets-wrapper">
                {% include 'page-elements/components/widgets/plus-icon.twig' with {
                    'widgetName'     : "add-note",
                    'id'             : "add-note",
                    'popoverContent' : 'notes.category.popover.createNote' | trans
                } %}
            </div>

        </div>
    </main>
{% endblock body %}

templates/modules/my-notes/new-note.html.twig
{% if ajax_render == false %}
    {% set template= "base.html.twig" %}
{% else %}
    {% set template= "blank.html.twig" %}
{% endif %}

    {% extends template %}

{% block body %}
    <main class='main-content bgc-grey-100'>
        <div id='mainContent'>
            <div class="container-fluid">

                {% include "modules/common/components/info-block.twig" with {
                    text_translation_string   : 'notes.infoBlock.text.mainDescription',
                    header_translation_string : 'notes.create.headers.newNote'
                } %}

                <div class="row">
                    <div class="col-md-12">
                        <div class="bgc-white bd bdrs-3 p-10 mB-20">
                            <section id="tiny-mce-wrapper" class="p-20 add-record-form">
                                {{ form_start(form,{'attr':{' data-entity':"MyNotes"}}) }}
                                {{ form_end(form) }}
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock body %}

templates/modules/my-notes/note-details.html.twig
{% if ajax_render == false %}
    {% set template= "base.html.twig" %}
{% else %}
    {% set template= "blank.html.twig" %}
{% endif %}

    {% extends template %}

{% block body %}
    <!-- ### $App Screen Content ### -->
    <main class='main-content bgc-grey-100'>
        <div id='mainContent'>
            <div class="container-fluid">
                {# Header achievements #}
                <div class="row">
                    <div class="col-md-12">
                        <div class="bgc-white bd bdrs-3 p-10 mB-20">
                            <h4 class="c-grey-900 mB-20 text-center">{{ note | capitalize }}</h4>
                            <section id="tiny-mce-wrapper" class="p-20">

                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock body %}

templates/modules/my-notes/settings.html.twig
{% if ajax_render == false %}
    {% set template= "base.html.twig" %}
{% else %}
    {% set template= "blank.html.twig" %}
{% endif %}

    {% extends template %}

{% block body %}
    <!-- ### $App Screen Content ### -->
    <main class='main-content bgc-grey-100'>
        <div id='mainContent'>
            <div class="container-fluid">

                {% include "modules/common/components/info-block.twig" with {
                    text_translation_string   : 'notes.settings.text.mainDescription',
                    header_translation_string : 'notes.settings.headers.settings.label'
                } %}

                <div class="row">
                    <div class="col-md-12">
                        <div class="bgc-white bd bdrs-3 p-10 mB-20">
                            <h4 class="c-grey-900 mB-20 text-center">{{ 'notes.settings.headers.categories.editCategory' | trans }}</h4>
                            {% include 'modules/my-notes/components/categories-settings.table.html.twig' %}

                            <h4 class="c-grey-900 mB-20 text-center">{{ 'notes.settings.headers.categories.addCategory' | trans }}</h4>
                            <div class="add-record-form">
                                {{ form_start(form,{'attr':{' data-entity':"MyNotesCategories"}}) }}
                                {{ form_end(form) }}
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </main>

{% endblock body %}